# Generated by Django 5.1.2 on 2024-10-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dealer name')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Dealer contact info')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type name')),
                ('is_bought', models.CharField(choices=[('bought', 'Bought'), ('not_bought', 'Not Bought')], default='not_bought', max_length=10, verbose_name='Item Bought Status')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Market name')),
                ('location', models.CharField(max_length=255, verbose_name='Market location')),
                ('contact_info', models.CharField(default='no info', max_length=255, verbose_name='Market contact info')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material name')),
                ('price', models.IntegerField(verbose_name='Material price')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Material color')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handmade.dealer')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='HandmadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Item name')),
                ('date_receipt', models.DateField(blank=True, verbose_name='Date of receipt')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Item picture')),
                ('customers', models.ManyToManyField(blank=True, related_name='handmade_items', to='handmade.customer', verbose_name='Customers')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handmade.itemtype', verbose_name='Item type')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handmade.market', verbose_name='Item market')),
                ('materials', models.ManyToManyField(to='handmade.material', verbose_name='Item material')),
            ],
            options={
                'verbose_name': 'Handmade Item',
                'verbose_name_plural': 'Handmade Items',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='handmade.customer', verbose_name='Customer Profile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
